data:
  dataset: METR-LA
  num_sensors: 207
  in_length: 12
  out_length: 12
  in_channels: 3
  out_channels: 1
  batch_size: 64

  train_prop: 0.7
  valid_prop: 0.1


trainer:
  early_stop: True
  early_stop_steps: 30
  print_frequency: 1

  weight_lr: 0.001
  weight_lr_decay_milestones: [50,60,70,80]
  weight_lr_decay_ratio: 0.1
  weight_decay: 0.00001
  weight_clip_gradient: 5

  arch_lr: 0.001
  arch_lr_decay_milestones: [50,60,70,80]
  arch_lr_decay_ratio: 0.1
  arch_decay: 0.00001
  arch_clip_gradient: 5

model:
  name: METR-LA_AutoSTF
  end_channels: 512
  hidden_channels: 32

  # best
  num_mlp_layers: 1

  # best
  IsUseLinear: True
  num_linear_layers: 4

  # best
  layer_names: ['TemporalSearch', 'SpatialSearch']

  # best
  num_temporal_search_node: 4
  temporal_operations: ['DCC_2', 'Informer']

  num_spatial_search_node: 5
  spatial_operations: ['GNN_fixed', 'GNN_adap', 'GNN_att']
  num_att_layers: 2
  num_hop: 2

