data:
  dataset: PEMS04
  num_sensors: 307
  in_length: 12
  out_length: 12
  in_channels: 3
  out_channels: 1
  batch_size: 64

  train_prop: 0.6
  valid_prop: 0.2

trainer:
  early_stop: True
  early_stop_steps: 30
  print_frequency: 1

  weight_lr: 0.001
  weight_lr_decay_milestones: [50,60,70,80]
  weight_lr_decay_ratio: 0.01
  weight_decay: 0.0001
  weight_clip_gradient: 5

  arch_lr: 0.001
  arch_lr_decay_milestones: [50,60,70,80]
  arch_lr_decay_ratio: 0.01
  arch_decay: 0.0003
  arch_clip_gradient: 5

model:
  name: PEMS04_AutoTF
  end_channels: 512
  hidden_channels: 32

#  num_mlp_layers: 3

  IsUseLinear: True
  num_linear_layers: 3

  layer_names: ['TemporalSearch', 'SpatialSearch']

  num_temporal_search_node: 4
  temporal_operations: ['DCC_2', 'Informer']

  num_spatial_search_node: 4
  spatial_operations: ['GNN_fixed', 'GNN_adap', 'GNN_att']
  num_att_layers: 1
  num_hop: 1
